### ISSUE TITLE
Error: A fixture file could not be found at any of the following paths:

### ISSUE THREAD

**Issue by oimtrust** [javieraviles/cypress-upload-file-post-form#1]
Hello. I got this issue, can you help me to solve this issue?

![image](https://user-images.githubusercontent.com/9985668/68369511-185c8100-016d-11ea-8855-a2cc4e96fedd.png)

**Comment by javieraviles** [comment]
so could you please provide a bit more of context please?

- When is that happening to you?
- Can I easily reproduce it?
- Is your code in a public repository?

anyway seems like your test is trying to use a `template_invoice.xlsx` that you should have prepared in `cypress/fixtures` path already before doing the tests and it is just not there..

**Comment by oimtrust** [comment]
This is my mistake ... I made a subdirectory in the fixture folder. and I only call the file name, the subdirectory should also be called. This problem is finished, thank you for your response.

**Comment by vishwa999** [comment]
@javieraviles Encountering same problem and not able to fetch data from fixtures file attached the screenshot and i am using default example.json file whoch i got by default.
![image](https://user-images.githubusercontent.com/26690445/73649204-4c303f80-46a5-11ea-8fc6-e4765cbde76a.png)
